source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'PSMobile'
platform :ios, '8.0'

link_with 'PSMobile','PSMobileTests'

pod 'spatialconnect', :path => './SC/spatialconnect-ios'
pod 'wkb-ios', :path => '../geopackage-wkb-ios'
pod 'FoldingTabBar', '~> 1.0.0'
pod 'zipzap', '8.0.6'
pod 'ReactiveCocoa', '2.5'
pod 'AFNetworking','~> 2.1'
